name: DockerBuild

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to add to docker image (comma separated)'
        required: false
        default: 'latest'

jobs:
  docker:
    if: github.repository == 'netmeld/netmeld'

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: netmeld/netmeld-dev
          tags: ${{ github.event.inputs.tags }}
      
